# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BGC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='BGCStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.BGC')),
            ],
        ),
        migrations.CreateModel(
            name='GCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('gcftype', models.CharField(max_length=200, null=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='MF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='MFGCFEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FloatField(null=True)),
                ('gcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.GCF')),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.MF')),
            ],
        ),
        migrations.CreateModel(
            name='MFStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.MF')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mfstrain',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Strain'),
        ),
        migrations.AddField(
            model_name='bgcstrain',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Strain'),
        ),
    ]
