# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgc',
            name='accession',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bgc',
            name='bgsclass',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bgc',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bgc',
            name='product',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
