# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-02 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GCFStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.GCF')),
            ],
        ),
        migrations.CreateModel(
            name='MF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MFStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.MF')),
            ],
        ),
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='mfstrain',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Strain'),
        ),
        migrations.AddField(
            model_name='gcfstrain',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Strain'),
        ),
    ]
