# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0002_auto_20171102_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFGCFEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FloatField()),
                ('gcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.GCF')),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.MF')),
            ],
        ),
    ]
