# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0003_mfgcfedge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mfgcfedge',
            name='p',
            field=models.FloatField(null=True),
        ),
    ]
