# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_auto_20171107_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGCGCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.BGC')),
                ('gcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.GCF')),
            ],
        ),
    ]
