# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_auto_20171103_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcf',
            name='gcftype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
