# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0005_bgcgcf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suid', models.IntegerField()),
                ('libraryid', models.CharField(max_length=1024)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Media')),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Spectrum')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumMF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.MF')),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Spectrum')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Spectrum')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Strain')),
            ],
        ),
        migrations.RemoveField(
            model_name='mfstrain',
            name='mf',
        ),
        migrations.RemoveField(
            model_name='mfstrain',
            name='strain',
        ),
        migrations.DeleteModel(
            name='MFStrain',
        ),
    ]
