# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0008_spectrum_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='libraryid',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
