# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0011_auto_20171108_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linker.Analysis'),
        ),
    ]
