# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0013_auto_20171108_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spectrum',
            old_name='suid',
            new_name='rowid',
        ),
    ]
