# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0014_auto_20171110_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgc',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gcf',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mf',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
