# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0016_spectrumstrain_parentmass'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='parentmass',
            field=models.FloatField(null=True),
        ),
    ]
