# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0018_spectrum_precursormass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiBIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('product', models.CharField(max_length=1024)),
                ('bgcclass', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=1024, null=True)),
                ('organism', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bgc',
            name='mibig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linker.MiBIG'),
        ),
    ]
