# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0019_auto_20171115_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgc',
            old_name='bgsclass',
            new_name='bgcclass',
        ),
    ]
