# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0020_auto_20171115_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfgcfedge',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
