# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0021_mfgcfedge_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCFClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
