# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0023_auto_20171128_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCFtoClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.GCF')),
                ('gcfclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.GCFClass')),
            ],
        ),
    ]
