# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0025_remove_gcf_gcftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcftoclass',
            name='original_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
