# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0026_gcftoclass_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcf',
            name='gcftype',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
