# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0027_gcf_gcftype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcf',
            name='gcftype',
        ),
    ]
