# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0028_remove_gcf_gcftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcf',
            name='n_strains',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mf',
            name='n_strains',
            field=models.IntegerField(null=True),
        ),
    ]
