# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0034_aaprobabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgcgcf',
            name='prob',
            field=models.FloatField(default=1.0),
        ),
    ]
