# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0035_bgcgcfprob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField()),
                ('intensity', models.FloatField()),
                ('spectrum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linker.Spectrum')),
            ],
        ),
    ]
